<?php 

/**
* This class is part of the core of Niuware WebFramework 
* and is not particularly intended to be modified.
* For information about the license please visit the 
* GIT repository at:
* https://github.com/niuware/web-framework
*/
namespace Niuware\WebFramework {

    /**
    * Process the URL to the correct route
    */
    class Router {

        private $path;

        private $view;

        private $error = true;

        private $admin = false;

        function __construct() {

            $this->initialize();

            $this->redirectFail();
        }

        /**
        * Parse the request URL and executes the routing
        */
        private function initialize() {

            if (BASE_PATH == "/") {

                $currentUri = substr(filter_input(SERVER_ENV_VAR, 'REQUEST_URI', FILTER_SANITIZE_URL), 1);
            } else {

                $currentUri = str_replace(BASE_PATH, "", filter_input(SERVER_ENV_VAR, 'REQUEST_URI', FILTER_SANITIZE_URL));
            }

            $this->path = explode('/', $currentUri);

            // If the URL is associated to a View, then load it
            if (isset(Settings::$views['main'][$this->path[0]])) {

                $this->redirectMain();

                $this->error = false;

            } else {

                $this->redirectTask($this->path[0]);
            }
        }

        /**
        * Executes the routing for Views (NOT API calls or admin Views)
        */
        private function redirectMain() {

            if (!$this->requireLogin()) {

                $this->view = Settings::$views['main'][$this->path[0]][0];

            } else {

                $this->view = "Login";
            }
        }

        /**
        * Verify if the View requires user login
        * @return bool Login required?
        */
        private function requireLogin() {

            $requireLogin = false;
            
            if (isset(Settings::$views['main'][$this->path[0]][1])) {

                $requireLogin = Settings::$views['main'][$this->path[0]][1];
            }

            return $requireLogin;
        }

        /**
        * Redirects to an API call or Admin view 
        * @return Api|View
        */
        private function redirectTask($action) {

            if ($action == "api") {

                include 'core/HttpInput.class.php';
                
                exit;
                
            } else if ($action == "admin") {

                return $this->setAdminMode();
            }
        }

        /**
        * Sets On the Admin mode (for Admin views)
        */
        private function setAdminMode() {

            $this->admin = true;

            $_SESSION['nwf_admin'.session_id()] = 1;

            $this->redirectAdmin();
        }

        /**
        * Redirects the browser to a default route, if an error was 
        * generated by the routing
        */
        private function redirectFail() {

            if ($this->error) {

                if (!$this->admin) {

                    header("Location: " . BASE_URL.HOMEPAGE);

                } else {

                    header("Location: " . BASE_URL_ADMIN.HOMEPAGE_ADMIN);
                }

                exit;
            }
        }

        /**
        * Executes the routing for Admin views
        */
        private function redirectAdmin() {

            if (!isset($_SESSION['nfw_admin_login' . SESSION_ID])) {

                $this->view = "Login.admin";

            } else {

                $this->view = Settings::$views['admin'][$this->path[1]][0] . ".admin";
            }

            $this->error = false;
        }
        
        /**
        * Returns a new instance of the requested View
        * @return View Instance of the view
        */
        public function getViewInstance() {
            
            $path = "\Niuware\WebFramework\Views\\" . $this->view;
            
            return new $path;
        }

        /**
        * Returns the name of the requested view
        * @return string View name
        */
        public function getViewName() {

            return $this->view;
        }

        /**
        * Verify if the current view is an Admin view
        * @return bool Admin view?
        */
        public function isAdmin() {

            return $this->admin;
        }
    }
}